### ISSUE TITLE
Scrapping

### ISSUE THREAD

**Issue by Kizuno18** [gd2003gamingchamp/utube-auto#3]
i got this issue while scrapping 

`Handling GoogleAPI
2022 8 14 18 42 3
./AUG_2022_v14.mp4
Scraping Videos...
Starting Scraping
JSON Query to removedmyusername/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
JSON Query to removedmyusername/feed/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/instaloader/instaloadercontext.py", line 348, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/instaloader/instaloadercontext.py", line 348, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/instaloader/instaloadercontext.py", line 348, in get_json
    raise QueryReturnedNotFoundException("Could not find \"window._sharedData\" in html response.")
instaloader.exceptions.QueryReturnedNotFoundException: Could not find "window._sharedData" in html response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/instaloader/structures.py", line 616, in _obtain_metadata
    metadata = self._context.get_json('{}/feed/'.format(self.username), params={})
  File "/usr/local/lib/python3.9/dist-packages/instaloader/instaloadercontext.py", line 386, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/usr/local/lib/python3.9/dist-packages/instaloader/instaloadercontext.py", line 386, in get_json
    return self.get_json(path=path, params=params, host=host, session=sess, _attempt=_attempt + 1)
  File "/usr/local/lib/python3.9/dist-packages/instaloader/instaloadercontext.py", line 374, in get_json
    raise QueryReturnedNotFoundException(error_string) from err
instaloader.exceptions.QueryReturnedNotFoundException: JSON Query to removedmyusername/feed/: Could not find "window._sharedData" in html response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/Desktop/YouTube-Automation-main/main.py", line 146, in <module>
    attemptRoutine()
  File "/home/user/Desktop/YouTube-Automation-main/main.py", line 137, in attemptRoutine
    routine()
  File "/home/user/Desktop/YouTube-Automation-main/main.py", line 91, in routine
    scrapeVideos(username = IG_USERNAME,
  File "/home/user/Desktop/YouTube-Automation-main/scrape_videos.py", line 19, in scrapeVideos
    profile = instaloader.Profile.from_username(L.context, username)
  File "/usr/local/lib/python3.9/dist-packages/instaloader/structures.py", line 561, in from_username
    profile._obtain_metadata()  # to raise ProfileNotExistsException now in case username is invalid
  File "/usr/local/lib/python3.9/dist-packages/instaloader/structures.py", line 623, in _obtain_metadata
    raise ProfileNotExistsException('Profile {} does not exist.\nThe most similar profile{}: {}.'
instaloader.exceptions.ProfileNotExistsException: Profile removedmyusername does not exist.
The most similar profile is: removedmyusername.
`

**Comment by gd03champ** [comment]
Problem seems to be with IG login.

Have you configured `config.py` file with your IG username and password?
If so, you may have given incorrect username.

If nothing helps, try with another IG account credentials.

**Comment by obigleo** [comment]
Isnot, i Just removed my username in this logs rrplacing text tô
removedusername

Em dom., 14 de ago. de 2022 22:41, GD ***@***.***> escreveu:
